### PR TITLE
Avoid error on missing statusN

### PR DESCRIPTION
**Pull request by scop**
I see errors like this in Home Assistant logs:
```
2020-09-21 22:50:33 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.samsung_m2070_series_2 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 469, in async_device_update
    await self.async_update()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/syncthru/sensor.py", line 158, in async_update
    self._attributes = {"display_text": self.syncthru.device_status_details()}
  File "/usr/local/lib/python3.8/site-packages/pysyncthru/__init__.py", line 124, in device_status_details
    status_display = [head.get("status{}".format(i)).strip() for i in [1, 2, 3, 4]]
  File "/usr/local/lib/python3.8/site-packages/pysyncthru/__init__.py", line 124, in <listcomp>
    status_display = [head.get("status{}".format(i)).strip() for i in [1, 2, 3, 4]]
AttributeError: 'NoneType' object has no attribute 'strip'
```

Untested fix in PR.

### CODE REVIEW

**Comment by nielstron** [comment]
Looks good! Thanks for the fix :) Please apply black formatting for the change to be merged.

**Comment by scop** [comment]
Done.

**Comment by scop** [comment]
(A pre-commit config that would take care of that and possibly other stuff would be nice ;))

**Comment by nielstron** [comment]
Great :)

> (A pre-commit config that would take care of that and possibly other stuff would be nice ;))

Sure, at the risk of making the development setup larger than the actual project :sweat_smile: Open for PRs ;)

**Comment by scop** [comment]
> Sure, at the risk of making the development setup larger than the actual project sweat_smile Open for PRs ;)

Nah, it's not that bad :) #43

**Pull request merged**
